### PR TITLE
Iss 2

### LINKED ISSUE #2: mobile nav has extra buttons
### Version

https://bridgetown-theme-bootstrap-blog.netlify.app

### Description

Looks like I forgot to remove the two buttons on the sidebar. For reference, this is the navbar component. It turns into a sidebar on mobile screens. 

Also see if you can make it swipe from the right and make those icons a bit smaller. 

<details open>
<summary>Additional Details</summary>
<br>

image

</details>

### Steps to reproduce

Open sidebar on mobile. 

### What is Expected?

Those buttons don't link anywhere and should be removed.

### PR DESCRIPTION
**Pull request by cjilbert504**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: Updating some css properties

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Here's an update to most of the points related to this issue. Getting the mobile nav to come in from the right is going to take me some more research into, I also modified some other layout things that felt a bit off to me when looking at the site.

### CODE REVIEW

**Review by andrewmcodes — APPROVED** [review]
This is great. TY!

**Comment by cjilbert504** [comment]
@andrewmcodes so I could be wrong but I think we can close this PR. But I think you need to push up the changes you made the other night when we paired on this.

**Comment by cjilbert504** [comment]
@andrewmcodes ok I just made one last change [0c20ba6](https://github.com/bt-rb/bridgetown-theme-bootstrap-blog/pull/5/commits/0c20ba64c59a8276aef0ec541079b5ea5a4ab5b6) to remove that break class I added 😅. So this should all be ready to go now.

**Comment by andrewmcodes** [comment]
Awesome work - ty

**Pull request merged**
